// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class AmazingFeature
{
    public int AmazingFeatureId { get; set; }

    public string Name { get; set; }

    public bool Deleted { get; set; }
}