// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Domain.Data;

public partial class AmazingFeatureContext : DbContext
{
    public AmazingFeatureContext()
    {
    }

    public AmazingFeatureContext(DbContextOptions<AmazingFeatureContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AmazingFeature> AmazingFeatures { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AmazingFeature>(entity =>
        {
            entity.ToTable("AmazingFeature");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}